#######################################################################
# This script analyzes a monophonic MIDI file generated by 
# sonification pipeline and produces several
# quantitative visualizations:
#   - Pitch distribution histogram,
#   - Combined plot of pitches and dynamics (velocity),
#   - Dynamics (velocity) over note index,
#   - Note duration distribution.
#
# These plots are exported as PDF files.
#
# Author: Hasan Babazada, Ph.D.
# Date: 02/20/2025
# Email: gasan4ik@hotmail.com
#
# Copyright (c) 2025 Hasan Babazada
# SPDX-License-Identifier: MIT
#
# This program is released under the MIT License.
# See the LICENSE file in the repository root for the full text.
#######################################################################

from mido import MidiFile
import matplotlib.pyplot as plt

# Load the MIDI file
midi_file_path = "PATH to MIDI file" # Replace with PATH to MIDI file
midi = MidiFile(midi_file_path)

# Initialize lists to collect data
pitches = []
velocities = []
durations = []
timestamps = []

# Extract note information
for track in midi.tracks:
    current_time = 0
    for msg in track:
        current_time += msg.time
        if msg.type == 'note_on' and msg.velocity > 0:
            pitches.append(msg.note)
            velocities.append(msg.velocity)
            timestamps.append(current_time)

# Calculate durations (difference between timestamps)
if len(timestamps) > 1:
    durations = [timestamps[i + 1] - timestamps[i] for i in range(len(timestamps) - 1)]
else:
    durations = [0] * len(timestamps)

# Visualization 1: Pitch Distribution
plt.figure(figsize=(10, 6))
plt.hist(pitches, bins=range(21, 109), color='skyblue', edgecolor='black')
plt.title("Pitch Distribution")
plt.xlabel("MIDI Pitch")
plt.ylabel("Frequency")
plt.grid()

# Save the first plot as a PDF
plt.savefig('pitch_distribution.pdf', format='pdf', dpi=300, transparent=True, bbox_inches='tight')
plt.close()  # Close the figure to free up memory

# Visualization 2: Mapped Musical Parameters (pitches + dynamics)
plt.figure(figsize=(12, 6))
plt.bar(range(len(pitches)), pitches, color='blue', alpha=0.6, label='MIDI Pitches')
plt.plot(velocities, color='red', marker='o', label='Dynamics (Velocity)')
plt.title('Mapped Musical Parameters')
plt.xlabel('Note Index')
plt.ylabel('MIDI Pitch / Dynamics')
plt.legend()
plt.grid()

# Save the mapped-parameters plot as a PDF
plt.savefig('mapped_parameters.pdf', format='pdf', dpi=300, transparent=True, bbox_inches='tight')
plt.close()  # Close the figure to free up memory

# Visualization 3: Dynamics Over Time (by note index)
plt.figure(figsize=(10, 6))
plt.plot(velocities, label='Dynamics (Velocity)', marker='o')
plt.title("Dynamics Over Time")
plt.xlabel("Note Index")
plt.ylabel("Velocity")
plt.legend()
plt.grid()

# Save the dynamics-over-time plot as a PDF
plt.savefig('dynamics_over_time.pdf', format='pdf', dpi=300, transparent=True, bbox_inches='tight')
plt.close()  # Close the figure to free up memory

# Visualization 4: Note Durations
plt.figure(figsize=(10, 6))
plt.bar(range(len(durations)), durations, color='orange', edgecolor='black')
plt.title("Note Durations")
plt.xlabel("Note Index")
plt.ylabel("Duration (ticks)")
plt.grid()

# Save the note-durations plot as a PDF
plt.savefig('note_durations.pdf', format='pdf', dpi=300, transparent=True, bbox_inches='tight')
plt.close()  # Close the figure to free up memory